### ISSUE TITLE
Status of InVision project/vendor representative

### ISSUE THREAD

**Issue by keywordnew** [design-tokens/community-group#13]
> currently reaching out to various design software vendors to get a representative from each one on the community group.

I'm opening this issue to look into the status of reaching out to @invisionapp. I'm happy to help with this, whether it involves connecting to the appropriate folks or lending a hand where needed in the initiative 🙌🏽 Love that y'all are coming together to create a tech-agnostic architecture for scaling design 💛

fwiw, I'm leaning on experience from other open source projects (@nodejs), education initiatives (@nodeschool), and foundations (@openjs-foundation).

**Comment by kaelig** [comment]
Hey Manil! Thanks for the support and proposing your help ❤️ 

As mentioned in the README, InVision is already in, with @ehudhal as its representative. It may not be known across the organization, so maybe you two can work together on spreading the word internally?

**Comment by keywordnew** [comment]
Thanks @kaelig 🙌🏽 I'll ping @ehudhal. Closing this issue for now as it seems resolved to me; feel free to reopen anytime.
