### ISSUE TITLE
Make path an optional but default property of the token.

### ISSUE THREAD

**Issue by reblim** [design-tokens/community-group#140]
Referring to [this paragraph](https://second-editors-draft.tr.designtokens.org/format/#groups-0:~:text=The%20names%20of%20the,with%20the%20following%20properties%3A) in the specification: 
`The names of the groups leading to a given token (including that token's name) are that token's path, which is a computed property. It is not specified in the file, but parsers that conform to this spec MUST be able to expose the path of a token. The above example, therefore, defines 4 design tokens with the following properties`

Why not we simply let "$path" be a default "optional" property of the token?

**Comment by TravisSpomer** [comment]
Can you explain a little more about what this would be helpful for? Would you use it for putting tokens in one part of the file but have their names actually be something different?

```json
{
  "Global":
  {
    "Color":
    {
      "Red": { "$value": "#ff0000", "$path": "MyColors.Red" }
    }
  }
}
```

**Comment by reblim** [comment]
The more I think about it, the less it makes sense. My main concern was around this specific part of the text: "parsers that conform to this spec MUST be able to expose the path of a token." but that will be always easy to extract for token parsers. So, I'm ok with parking (closing) this one for now.
