### ISSUE TITLE
Include mathematics in the format specification

### ISSUE THREAD

**Issue by lauthieb** [design-tokens/community-group#153]
Hello,

_First of all, a huge thank you to all the people who have contributed so far to this wonderful initiative.
Being passionate about UI and standardization, I loved reading the second draft and I want to be part of the contributors by proposing some changes that I hope you will like._

## Context

I really liked the section about aliases/references.

<img width="884" alt="CleanShot 2022-07-01 at 02 19 51@2x" src="https://user-images.githubusercontent.com/9600228/176798954-3fa5f70f-24d3-4c52-93ba-2986e5c34ec0.png">

And that's where I got an idea. 

## Proposal

How about adding a notion of mathematics _(cf. [calc, min, max](https://www.w3schools.com/css/css_math_functions.asp), [hsl](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl), [hsla](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsla), etc. in CSS for example)_ within the format specification?

A use-case would be to apply mathematics to generate one color from another.

What do you think about this?

Thanks in advance for your opinion!

**Comment by TravisSpomer** [comment]
This is covered in #81 and #88.

**Comment by lauthieb** [comment]
Thank you @TravisSpomer for this info. I will close this issue in favor to those issues.
