### ISSUE TITLE
Spec/CG status

### ISSUE THREAD

**Issue by romainmenke** [design-tokens/community-group#170]
It has been some time since the CG invited implementations https://www.w3.org/community/design-tokens/2022/06/14/call-to-implement-the-second-editors-draft-and-share-feedback/

A lot of feedback has been given by the community but there has been very little dialog with spec editors.

This current draft imho has serious issues and is not ready for implementations.
I would like to avoid that too many tools, design programs, ... adopt the current draft.

Can we get an update on the spec/CG status and when issues will be addressed?

**Comment by kaelig** [comment]
Hi Romain, thank you for asking about the status of the spec!

The past few months have been a little quiet in part because of the summer holidays!

The team is reviewing all the feedback and discussing critical areas of the draft with 4 major players in the design tooling field. They're implementing the specification and giving us feedback about what works and what doesn't. They know the spec is a work in progress and be assured they won't release anything publicly without considering the community's feedback too.

(I don't have a timeline for when all the issues will be addressed)

**Comment by romainmenke** [comment]
> The team is reviewing all the feedback and discussing critical areas of the draft with 4 major players in the design tooling field. They're implementing the specification and giving us feedback about what works and what doesn't. They know the spec is a work in progress and be assured they won't release anything publicly without considering the community's feedback too.

Can this work be done following the charter commitments?
I would expect this work to be done in public.

https://github.com/design-tokens/community-group/blob/main/CHARTER.md#transparency

**Comment by romainmenke** [comment]
That is disheartening.

I understand that a private channel/space is useful for some companies to discuss high level features before these go public.

But this is in conflict with the goal and purpose of a w3c community group to design a file format.
At this point I am unsure how much credibility this format will have.

Can you clarify the CG's commitment to its charter and the transparency section therein.

**Comment by kaelig** [comment]
We remain committed to communicating publicly by default.

We're also making adjustments so we can collect critical feedback from tool makers in ways they're comfortable with.

Once we reach the first implementation milestone, I will work on moving these conversations to the open.

**Comment by romainmenke** [comment]
@kaelig I am unsure how this works in practice?
It sounds like we have a split track.

- track A: select corporations
- track B: the rest of the community

If part of the design work of the format is done for long periods of time on track A then the community is giving feedback on a format that no longer exists.

Track B has no knowledge of the current state of the format.

The call to implement is now also a bit weird : https://twitter.com/DesignTokens/status/1536761206823739393

What are we implementing and giving feedback on?

----

Another concern is conflicting feedback.
The current state seems and feels as if track A is prioritised and feedback on track B is largely not acted on.

Since we can not see anything from track A, are they aware of the feedback given here?

------

All these concerns and many more are exactly why transparency and doing all design work in public is part of the W3C process.

**Comment by romainmenke** [comment]
That this has gone unanswered for so long can only be interpreted as a confirmation to my concerns :/

**Comment by kaelig** [comment]
This has gone unanswered because your concerns are unfounded, and I have no interest in arguing about your false interpretation of group politics.

The current state of the format is what you see on GitHub, period.
