### ISSUE TITLE
Add support for escaping

### ISSUE THREAD

**Issue by ChucKN0risK** [design-tokens/community-group#171]
The only thing that really sticks out in my mind as high pri for v1 here is escaping, because it permanently prevents some input. IMO we should do something like escape characters (`\.`) to ensure it's possible to:
- Create `{`  in string values that could also contain references, e.g. `{ $type: "fontFamily", "$value": "Font name with \\{ and \\} in it" }`
- Use . and } in variable names without breaking , e.g. `"Wide Box Width 2\\.0"`

Everything else I've thought of so far, to my mind, can be (somewhat) cleanly added or changed in future versions without invalidating old files. (If we ever did expression support, that might get harder.

Escaping is going to be importantly largely because people will autogenerate these files based on names they have specified elsewhere, in languages or formats that do support dots. I've had a lot of times where I want to keep values in sync across several languages and I'm always sad at the amount of destructive name transformations I have to do (which often ends up with invalid characters replaced with `_`, making them potentially non-unique).

**Comment by romainmenke** [comment]
see : https://github.com/design-tokens/community-group/issues/167

**Comment by ChucKN0risK** [comment]
The editors group reviewed this issue and decided to close it as it's a duplicate of #167.
