### ISSUE TITLE
Support json5 in format

### ISSUE THREAD

**Issue by lukasoppermann** [design-tokens/community-group#175]
Hey,

[`json5`](https://json5.org/) brings a lot of convenience into json files but also allows for comments. As design token files are and probably will in the foreseeable future be at least partly interacted with manually, allowing comments can be very helpful.

I would love to suggest 2 updates to [the format specs](https://design-tokens.github.io/community-group/format/#file-extensions):
1. add `.tokens.json5` to the allowed extensions
1. make `.tokens` a `json5` schema

**Comment by felixhaeberle** [comment]
+1 I would **love** to write comments in design token files + there are much more possibilities: 

```json5
{
  // comments
  unquoted: 'and you can quote me on that',
  singleQuotes: 'I can use "double quotes" here',
  lineBreaks: "Look, Mom! \
No \\n's!",
  hexadecimal: 0xdecaf,
  leadingDecimalPoint: .8675309, andTrailing: 8675309.,
  positiveSign: +1,
  trailingComma: 'in objects', andIn: ['arrays',],
  "backwardsCompatible": "with JSON",
}
```

**Comment by TravisSpomer** [comment]
I love the convenience of things like JSON5, but not the prospect of any code that wants to support reading design tokens files also having to include a JSON5 parser package. It also might be impossible right now given the state of JSON5 not (to my knowledge) being standardized or fully open; the spec appears to be MIT-licensed.

Maybe this could be accomplished by the spec stating that any conforming parser MAY use the data if it is in a format that is *compatible* with JSON like JSON5 or (shudder) YAML, but only JSON is truly valid. Then token transform tools could ship a JSON5 parser and say that *its* allowed input formats are JSON and JSON5, without requiring that *every* tool also support JSON5. In that case people could use JSON5 whenever all of the tools they plan to use are compatible, but maybe they'd have to convert it to JSON first to use it with something someone threw together on a personal `github.io` page and didn't want to include a JSON5 package.

**Comment by kaelig** [comment]
JSON itself is defined across 4+ standard bodies, and JSONC/JSON5 are great for authoring JSON, but not as great (at the moment) as an interchange format over the wire, for example between browsers.

Follow this discussion on the TC39 repo, as it might one day unlock this capability for us: https://github.com/tc39/proposal-json-modules/issues/14

**Comment by PavelLaptev** [comment]
JSON5 looks good, but I agree with @TravisSpomer simple JSON fits better here because it's simple and just works everywhere. Also, I think that comments shouldn't be in a tokens file, mostly it's not a code that you're writing manually, probably it will be generated automatically.

**Comment by c1rrus** [comment]
I agree with @TravisSpomer and @kaelig on this. JSON5 (and other supersets of JSON like JSONC) are not as broadly supported as JSON. Many programming languages can parse JSON out of the box, but formats like JSON5 would necessitate pulling in additional libs (assuming they're even available).

I'm not sure if the spec should explicitly allow parsers to support formats besides JSON. However, I see no reason why a parser couldn't support other file formats besides the DTCG one, such as DTCG-in-JSON5 or even something entirely different 😉.

Another approach might be to create a pre-processor. Just like we havr Sass, LESS and others for

**Comment by kevinmpowell** [comment]
The spec editors have reviewed this issue and decided to stick with JSON as the format at this time.
