### ISSUE TITLE
colorPalette composite type

### ISSUE THREAD

**Issue by drwpow** [design-tokens/community-group#178]
I’d like to propose a composite type of [**color** (8.1)](https://tr.designtokens.org/format/#color) that would allow colors related to one another to have a more clear association (and be able to use this association in tooling).

The concept of a palette is present in most design systems (e.g. [Adobe Spectrum](https://spectrum.adobe.com/page/color-system/), [IBM Carbon](https://carbondesignsystem.com/guidelines/color/overview/#contrast-ratios), as well as design system tooling (screenshot):

![Screenshot of supernova.io’s palettes](https://user-images.githubusercontent.com/1369770/199614618-0f99af69-2cd9-4753-a784-f9b4aeff863c.jpg)

I’d like to offer 2 possible ways to represent this:

### Option 1: array

```json
{
  "blue-50": {
    "$type": "color",
    "$value": "#4589ff"
  },
  "blue-palette": {
    "$type": "colorPalette",
    "$value": [
      "#edf5ff",
      "#d0e2ff",
      "#a6c8ff",
      "#78a9ff",
      "{blue-50}",
      "#0f62fe",
      "#0043ce"
    ]
  }
}
```

This allows colors to have not only a direct relationship with one another, but a specific ordering as well. The meaning of the ordering would be up to the author (e.g. light-to-dark vs dark-to-light).

The array format would slot in neatly with what most design systems are doing already that use values like `Blue 10`, `Blue 20`, etc. ([Adobe Spectrum](https://spectrum.adobe.com/page/color-system/), [IBM Carbon](https://carbondesignsystem.com/guidelines/color/overview/#contrast-ratios)). Only this would be a universal way to describe palettes rather than having to infer them based on numbers in the token name.

I really don’t see a downside to this method.

### Option 2: semantic boundaries

```json
{
  "blue-50": {
    "$type": "color",
    "$value": "#4589ff"
  },
  "blue-palette": {
    "$type": "colorPalette",
    "$value": {
      "light": "#edf5ff",
      "mid": "{blue-50}",
      "dark": "#0043ce"
    }
  }
}
```

A more experimental approach: the palette is described in terms of the middtone, and the lightest and darkest colors in the palette. This is essentially an array but with limited values, and with names. Though unlike the array, this couldn’t be used without tooling, and given that so much info like colorspace and easing curve is omitted (for an example see [colorbox.io](https://colorbox.io/)), the implementations would vary so wildly this may not be worth pursuing. But wanted to toss it out there just as an idea.

---

Thoughts on the proposals?

**Comment by landondurnan** [comment]
I think the challenge with the array proposal is there's no clear way of knowing what tokens would be generated based on the hex values. While many systems have adopted a numerical scale that represents the lightness / darkness of a color, it's not always multiples of 10s. I've seen just as many use multiples of 100s. There's also many cases that omit or add steps based on the luminosity, for example [Material 3 adding a `95` and `99` in it's scale](https://m3.material.io/styles/color/the-color-system/key-colors-tones). While the differences in the actual tokens is very similar, I think many systems would be very opinionated on the key and values being closely linked to how that system thinks about color.

As I understand the semantic boundaries proposal, something like this seems like it's already doable by choosing values that  have more meaning or creating additional aliases. `$color-blue-50` == `$color-blue-mid`. Is the suggestion to limit to only three values (light, mid, dark)? I've found often that's not enough.

**Comment by caoimghgin** [comment]
I've been thinking about colors for design systems and how difficult it is to find a universal consensus. I made the [Genome Color Tool](https://www.genomecolor.space/) that offers various popular color system 'optimizations' that are aligned to WCAG standards. I'm opinionated on using semantic names ('primary', rather than 'blue') but I believe it is possible that we can define a limited set of popular color systems and systemically generate tints/shades (which will need further definition as contextual definitions 'color-background-button-primary-hover'). In any case, hard to recommend an array of hex values automatically generated from a single base color IMHO.

**Comment by drwpow** [comment]
> it's not always multiples of 10s. … There's also many cases that omit or add steps based on the luminosity

That’s a very great point. There is no one true way of deriving these values, and even the most methodical systems do have half-steps like you said.

The array approach is more of a very practical usage of a color gradient, because take away all the keys and you do have stepped color that you usually adjust by a value or two to get the right contrast. And so this proposal would be to have a more generic approach by not getting into the differences of those keys.

But also to your point, those keys are important to some systems, and do carry meaning. And for those systems I guess that would just be better served with groups that exist in the spec now. But I’d still think that many systems do operate like more of an array, and regardless of absolute values between the steps, do think of the gradient more like a type scale, and often step “up” or “down” more fluidly as needed.

> Is the suggestion to limit to only three values (light, mid, dark)? I've found often that's not enough.

To be honest this was more a half-baked attempt at interpolating colors, but after reading your thoughts I’m thinking that won’t be practically possible. So I’d probably just say “let’s forget about the semantic boundary approach” 😄

**Comment by drwpow** [comment]
> In any case, hard to recommend an array of hex values automatically generated from a single base color IMHO.

Yes I agree! The 2nd proposal was attempting that but the more I thought about it, the ways of generating colors are as different as color tokens themselves! But for clarity in the array approach nothing is generated; it’s only a defined ordering of manually-selected colors. The one alias is only there as an example to show colors _can_ be aliased with semantic names if desired, but that’s not a requirement.

> I made the [Genome Color Tool](https://www.genomecolor.space/)

This looks great! And yeah capturing this idea is what I’m wondering if there’s a standard that could be formed here. If you had to suggest a syntax for these color scales what could capture this? Or do you think the standard of having keys for each step is still best (even if it’s numeric)?

**Comment by PavelLaptev** [comment]
I think we can wrap a palette [as a group](https://second-editors-draft.tr.designtokens.org/format/#additional-group-properties). To have only a color code could be not enough, sometimes there should be a description for each color.

**Comment by caoimghgin** [comment]
Recently I've been diving deeper into Figma plugins to export tokens (currently 'Design Tokens') and then formatting to the desired output by custom parsers/transforms/filters in StyleDictionary. As @PavelLaptev suggests, I put SemanticWeighted (base) colors in a group called palette.

```
{
  "color": {
    "palette": {
      "primary": {
        "primary015": {
          "$type": "color",
          "$value": "#f6f8f6ff"
          }
        },
        "primary025": {
          "$type": "color",
          "$value": "#eef1efff"
          }
        },
        "primary050": {
          "$type": "color",
          "$value": "#dde4dfff"
          }
        }, ...
```

With a StyleDictionary parser, I can see these are semantic and can map to contextual colors (replacing the hex values optimistically).

```
{
  "color": {
    "contextual": {
        "light": {
            "brandBackground10": {
              "$type": "color",
              "$value": "{primary015}",
          },...
        "dark": {
            "brandBackground10": {
              "$type": "color",
              "$value": "{primary800}",
          }
```

Overall, I suspect any further 'optimization' of structure would tend to be prescriptive to doing things a certain way. And if I had to be opinionated, I'd lean towards being as flat as possible where it comes to 'primitive' tokens.

**Comment by kevinmpowell** [comment]
The format editors have reviewed this issue. At this time we've decided not to add an additional type, `colorPalette` to the spec, for many of the reasons mentioned in this thread. 

Naming, grouping, and deciding "stops" of color are all nearly impossible to standardize, and don't align with the "universal" goal of this format. The spec is intentionally unopinionated on naming or organization of tokens, allowing the groups to be used however authors and vendors see fit.

As for the array/ordering proposed in Option 1, we don't feel it's a good fit for the spec. From our perspective, the arrangement/relationship of colors is largely a documentation concern, and again, may vary from author to author. Including the Option 1 proposal is akin to us "taking a stance" on how to organize and structure your tokens, which runs counter to our approach to the spec thus far.
