### ISSUE TITLE
Use CSS as a transfer format instead of JSON.

### ISSUE THREAD

**Issue by romainmenke** [design-tokens/community-group#185]
Because I can't help but wonder if JSON was picked only because it is the go-to format to communicate data between programs. I want to make sure this choice was the right one.

------------

A lot of the work being done here in the DTCG has been done before by the CSSWG.

- type definitions
- property definitions
- language syntax
- language grammar
- ....

With CSS we already have a way to communicate style information in a structured, machine readable manner.

There is also a very large and healthy community around it.
There are parsers and serialisers in many programming languages.

Instead of inventing something new and trying to force it to work in JSON I propose we just use CSS.

```json
{
  "shadow-token": {
    "$type": "shadow",
    "$value": {
      "color": "#00000088",
      "offsetX": "0.5rem",
      "offsetY": "0.5rem",
      "blur": "1.5rem",
      "spread": "0rem"
    }
  }
}
```

could be :

```css
/* file: brand.tokens.css */
@token shadow-token {
  box-shadow: 0.5rem 0.5rem 1.5rem #00000088;  
}
```

Groups can be done in multiple ways :

```css
@token your-group {
  @token shadow-token {
    box-shadow: 0.5rem 0.5rem 1.5rem #00000088;  
  }

  /* more tokens */
}

/* override a single token from a group */
@token your-group.shadow-token {
  box-shadow: 0.5rem 0.5rem 1.5rem pink;
}
```

Custom properties already exist :

```css
@token shadow-token {
  box-shadow: 0.5rem 0.5rem 1.5rem #00000088;  
  --something-specific-to-my-tool: "hello";
}
```

-----

Starting out with support for everything in the CSS specification will be impossible.
But a small subset can be defined and can be expanded over time.

It allows the DTCG to focus on these aspects :

- definition of the custom `@token` at rule
- definition of the adopted subset of the CSS specification

**Comment by lukasoppermann** [comment]
But this means every tool that wants to transform tokens needs to write parsing logic. Also output may not be css but xml for android or other files e.g. for swift. This means css properties need to be parsed into a json like shape to re-structure to other languages.

**Comment by romainmenke** [comment]
> But this means every tool that wants to transform tokens needs to write parsing logic.

Parsers, serialisers exist for most languages.
More can be created.

> Also output may not be css but xml for android or other files e.g. for swift.

The same is true for JSON.

> This means css properties need to be parsed into a json like shape to re-structure to other languages.

The same is also true for JSON.
Only JavaScript has a special relationship with JSON.

All other programming languages need to parse to their equivalent.

-----

I definitely do not mean that CSS is a better or more common data format.
It is not.

But the CSSWG has done so much work to create ways to record visual/style information in a file. Not building on top of that seems like a waste.

Declaring design tokens is something that can be done in CSS and I think it is worth further exploring the benefits of such an approach.

**Comment by lukasoppermann** [comment]
>The same is also true for JSON.
> Only JavaScript has a special relationship with JSON.
>
> All other programming languages need to parse to their equivalent.

What I meant to say is that JSON is a standard that has ready to use parsers in nearly all languages.

> For CSS as a language :
> Parsers, serialisers exist for most languages.

I was / am not aware of that. So there are css to property parsers? One would need to turn `0.5rem 0.5rem 1.5rem pink` into individual properties to use in tools that don't have a css like syntax.

**Comment by romainmenke** [comment]
There is definitely a tradeoff here. They are both better in different aspects.

Using JSON as a format has benefits because the format is simpler and has wide support for parsers/serialisers.

CSS would be easier because the specification work for all the needed value types has already been done.

Working together with the CSS tooling community would also have benefits for the design token tooling community.

**Comment by romainmenke** [comment]
> 1. It will take time to figure declarations inside like arrays, strings numbers all these types how we show them? CSSOM doesn't have these basic types that all programming languages have.

Can you give concrete examples of something that isn't possible to express in CSS syntax?
Lists of values can easily be expressed in CSS with a comma separated list : `a, b, c, d, ...`

> 2. Actually, you don't need to parse JSON inside SWIFT environment, e.g. packages like Style Dictionary or others will do that using JS. And JS has the native JSON support.

If the argument is that an intermediary tool is doing the heavy lifting then the same would be true when using CSS as a file format. An intermediary tool around JSON could be replaced by an intermediary tool around CSS.

> 3. We are not inventing a new format or rules, but mixing CSS syntax with something else, yes. JSON has its rules, and structured better then CSS — simpler.

I don't follow this statement and don't understand what you mean with this.
Can you elaborate?

> 4. Unfortunately, we can't fully use all props and options we have in CSS because it's not possible to transpile them for other platforms, like animation props. We will need to write them not like in CSS.

I don't expect design tokens to.
I made it clear that the DTCG would need to define the parts of the CSS specification it intends to adopt.

> 5. The goal is not support the web, but create something that could be transpiled to other platforms as well.

The web does not benefit from this approach.
Using the CSS syntax and value definitions does not mean that the file is usable as CSS for a web project.

We would only use the CSS syntax and value definitions to get a head start for a transfer file format.

**Comment by equinusocio** [comment]
One of the core principles of design tokens is that they are platform agnostic because they MUST be usable in differnt implementation/design. A single design tokens must support other platforms too, that's why they have to be raw data and then transformed for the supported platforms.

CSS is already a domain-specific (or platform-specific), and so is one output language, more precisely the one for web-based implementations (but there are many supported formats on web). It cannot be the initial format for tokens then, the same way design tokens unlikey hold css-specific values like `rem`, `%` etc...

**Comment by romainmenke** [comment]
I think you misunderstood what I meant with this proposal :)

I do not mean to encode design tokens as CSS that would work in a browser.
This would never work because there is no document tree to match things against.

I meant to use CSS as a basis for a storage format.

```css
/* file: brand.tokens.css */
@token shadow-token {
  box-shadow: 8 8 24 #00000088;  
}
```

This is syntactically correct CSS and uses existing specifications for parsing, serializing.
It also uses existing specifications for values and properties.

It however does nothing in a browser.
If you want to use this token in CSS you would need to convert it just like you would need to for iOS or any other platform.

-----

In a way this is a counter point to :

- https://github.com/design-tokens/community-group/issues/120
- https://github.com/design-tokens/community-group/issues/121

There seems to be resistance to making the specification lean and easy to consume in software.

This proposal embraces the reasons behind that :
- easy to read/write for humans
- very forgiving so that anyone can experiment with custom things not (yet) in the specification
- reducing the surface the specification needs to define

**Comment by romainmenke** [comment]
I know this change will never happen.
But I still think it is valuable to not always pick JSON as the one and only data format.

Many issues that are being raised here are the result of inventing yet another way to encode style/visual data. This work was already done for CSS by the CSSWG.

CSS isn't widely seen as something that can be used outside the browser, but it can and doing so can have benefits.

**Comment by equinusocio** [comment]
It would make sense, i agree, but i see this as "evolution" of a standard. It may be an alternative syntax (like json vs. yaml) but at current states i think we should focus on having one standard at least.

**Comment by romainmenke** [comment]
> we should focus on having one standard at least

Absolutely :)

**Comment by kevinmpowell** [comment]
We've reviewed this issue. There's some good points here, but we're sticking with JSON as the Design Tokens format for now.

**Comment by romainmenke** [comment]
Thank you for going of this here :)
