### ISSUE TITLE
[Documentation] Add translator tool

### ISSUE THREAD

**Issue by mark-nicepants** [design-tokens/community-group#209]
I created a translator for these json design token files that interprets the tokens and creates useful Dart/Flutter code. Maybe it can be added to the Translators section in the design doc.

More info here:
https://github.com/mark-nicepants/figma2flutter

Would love some feedback if anyone has the time to look through the code!

**Comment by c1rrus** [comment]
Your tool looks neat! Thanks for sharing.

However, I think translation tools we list in [our glossary's examples](https://tr.designtokens.org/format/#translation-tool) are already sufficient to illustrate what we mean by "translation tool", so I'm not sure adding yours (or indeed others like [Cobalt](https://cobalt-ui.pages.dev/) or [Design Tokens CLI](https://github.com/Heydon/design-tokens-cli)) is necessary.

However, I've been thinking for a while now, that it would be great to make a list of tools that support the DTCG file format. Perhaps this is something that could eventually live on the [DTCG website](https://www.designtokens.org/). Perhaps for now, I'll create a GitHub issue where folks can share their tools in the comments.

**Comment by c1rrus** [comment]
FYI: I've added an issue inviting folks to share tools they've made that can read or write DTCG files: https://github.com/design-tokens/community-group/issues/211

I'm not sure if Figma2Flutter qualifies though as it sounds like it reads Token Studio's format, which is not the same as the DTCG format. I'm aware that the Token Studio folks intend to support the DTCG format (and their own is already quite close to it) but, as far as I know, it does not _yet_.

However, if/when Figma2Flutter supports the DTCG file format, please add it to that issue. Thanks!

**Comment by kevinmpowell** [comment]
There's also this list of Design Token Tools: https://github.com/sturobson/Awesome-Design-Tokens which is probably a better place to promote your tool @mark-nicepants
