### ISSUE TITLE
Do we have a discussion channel to speed up feedback?

### ISSUE THREAD

**Issue by mnrendra** [design-tokens/community-group#212]
Do we have a channel to speed up the discussion (like Slack or Discord)? So that GitHub issues can be followed up asap and speed up pull-request reviews. I think if we had a discussion channel like Slack or Discord, it could speed up the standard release of Design Token.

**Comment by mnrendra** [comment]
Thank you @kaelig, but when I clicked [https://join.slack.com/t/design-systems/shared_invite/zt-1hx6rbtiq-vKg81ltcYhCIi58M9OT__w](https://join.slack.com/t/design-systems/shared_invite/zt-1hx6rbtiq-vKg81ltcYhCIi58M9OT__w) that provided from [https://www.design.systems/](https://www.design.systems/) it says "This link is no longer active"

**Comment by kaelig** [comment]
Sorry about that, can you try this link instead? https://join.slack.com/t/design-systems/shared_invite/zt-1sxxyavas-RabCGFzQZ19bU7R49Xrkng

**Comment by romainmenke** [comment]
It is helpful if any discussions on slack/discord/... are recorded/transcribed in some way and reported back in the relevant github issues.

This is more inclusive to the whole community and makes it possible for more people to give feedback.

**Comment by kaelig** [comment]
Agreed, Slack is useful for high-bandwidth communication and asking questions, but any important decision must be documented and argued over on GitHub.

**Comment by kaelig** [comment]
Closing this, as it feels like this question was resolved.
