### ISSUE TITLE
[Closed] 📣 Call for specification editors

### ISSUE THREAD

**Issue by kaelig** [design-tokens/community-group#38]
Dear group members, today we're excited to start our first call for editors 🎉 

One of the DTCG’s main goals is to produce a specification.

The specification is broken into multiple modules:

- Format (the language and its grammar)
- Colors
- Spacing
- Easing
- (more to come!)

We need 2 to 3 editors per module, ideally representing various interests: design tool makers, design system creators and maintainers, users of design systems, as well as design token tool makers.

**[Read the full call for editors](https://docs.google.com/document/d/12Nh1LIYw_9jQKpceLPWOa73VZeTo_YidzLQPTuiYMww/edit#)** (in Google Docs) to learn more and apply to become an editor.

Looking forward to hearing from y'all!

@jina & @kaelig

**Comment by jina** [comment]
This is so exciting!

**Comment by sogen** [comment]
Still open? interested In Colors and how to use them as tokens with developers.

**Comment by kaelig** [comment]
The call for editors ended on February 14th – @jina and I are currently reviewing applications and will get back to applicants over the next 2 weeks for individual chats.

@sogen you may contribute to the specification on GitHub and by attending upcoming workshops and meetings – [join the community group](https://www.w3.org/community/design-tokens/) and watch this repository to stay in the loop!

**Comment by kaelig** [comment]
Closing as part of an issue cleanup.
