### ISSUE TITLE
Editors, kick-off & research meeting notes (+ slides), next steps

### ISSUE THREAD

**Issue by kaelig** [design-tokens/community-group#39]
Hi everyone,

## Summary

1. We found editors for most modules: format, colors, animation, spacing (we need more folks, please reach out if you're interested), and a few people also joined the team for support and to work on the education track (website, documentation, etc.)
1. We had a kick-off meeting ([slide deck](https://docs.google.com/presentation/d/1DbAe4RtQszoGYC6YNNWoo9xSpFwXgLW3X3YEjQ3aw0U/edit?usp=sharing)) on June 25th.
1. Research groups gathered resources (see below):
    1. The state of design tokens
    2. Syntax and language
    3. Stakeholder mapping
    4. Future of tokens
1. Our current priority: write drafts for the specification, so we can involve design tool makers in the discussion

## Next steps

1. Align on the "why", principles, and scope
1. First editors’ draft for the format module
2. Drafts for other modules
3. Second editors’s draft for the format module
4. Review by implementers (makers of popular design tools)
5. Rince and repeat and see the technical recommendation mature

The team is also working on collecting the findings of these research groups, and will publish some of them on the website (work in progress).

---

## Editors

![Screen capture of the Zoom window during the DTCG kick-off meeting](https://i.imgur.com/sKr26xh.jpg)

Jina and I reviewed more than 25 applications for editorship, met ~20 out of them, and we now have a team of dedicated editors, as well as some folks who'll be working on the website, community, and educational aspects. The questions we asked them were around experience, availability, and what they expected to get out of this experience.

The practitioners working on the Design Tokens W3C Community Group’s core team are:

- Adam Sedwick
- Donna Vitan (editor)
- James Nash (editor)
- Adekunle Oduye (editor)
- Ayesha Mazumdar (editor)
- Caleb Williams
- Danny Banks (editor)
- Garth Braithwaite
- Johan Stromqvist (editor)
- Kathleen McMahon (editor)
- Kevin Powell (editor)
- Louis Chenais (editor)
- Matt Felten (editor)
- Nathan Curtis
- Val Head (editor)
- Zack Brown (editor)

---

## Kick-off meeting

On Thursday, June 25, 2020, @jina and myself led a kick-off meeting ([slide deck](https://docs.google.com/presentation/d/1DbAe4RtQszoGYC6YNNWoo9xSpFwXgLW3X3YEjQ3aw0U/edit?usp=sharing)) with the core team of the Design Tokens W3C Community Group.

We gave the team some historical context, and then provided prompts to the team who was instructed to work in 4 separate research groups.

---

## Research groups

Jina and I assigned people into 4 research groups, with these instructions:

> Each group (unrelated with the modules) will research specific topics over the next 2 weeks and will have 15 minutes to present their findings during our next meeting.
> Go as deep as you want, the research will help make better spec decisions, will be published, and could lead to blog posts later on (edited by the folks who will work on the education track).

We gave each group prompts to help them focus their research in a direction we were expecting, with some nuance:

> These prompts are suggested to help you find inspiration. They can be rephrased or skipped if you find areas that would require more attention. Go as deep as you’d like into these topics. Make sure to mention your sources and recognize authors/articles you’re quoting.

### The state of design tokens

Danny, Kathleen, Louis, Nathan.

- What are examples of teams currently using tokens, and what trends seem to emerge (tools, languages…)?
- Related: is design or development the starting point, as in: what do teams consider as their source(s) of truth?
- How do design tools and plugins implement tokens today?
- What community traction do design token tools have (DSM, Style Dictionary, Theo, Diez, theme-ui, Lona…)?
- How is accessibility considered by teams using tokens?

### Syntax and language

Donna, James, Kevin, Zack

- What are the pros and cons of creating a new format/syntax?
- What are the pros and cons of relying on an existing format/syntax?
- What are relevant examples of specifications that created a new format/syntax?
- What are relevant examples of specifications that relied upon or augmented an existing format/syntax?

### Stakeholder mapping

Ayesha, Garth, Matt

- Who at each implementer company should we proactively talk to and put in the loop? (Adobe, Figma, Framer, Sketch…)
- Consider product managers and decision makers, as well as influencers/advocates within these companies.

### Future of tokens

Adam, Caleb, Val

- What design token tools are coming up?
- What doors will interoperability open in making the design and development process better?
- Optional: How could no-code tools such as Webflow, Shopify, Squarespace… make use of design tokens (webhooks, APIs, …)?
- Optional: Beyond digital product design: Google Docs themes, experiential marketing, IoT lighting…
- Optional: What might we see in the far future? (GUIs, AI/ML-driven generative design, design linting, accessibility linting…)

**Comment by chasemccoy** [comment]
> we need more folks, please reach out if you're interested

@kaelig What's the best way to reach out?

**Comment by kaelig** [comment]
Hey Chase, please follow the instructions in the original [Call for editors](https://docs.google.com/document/d/12Nh1LIYw_9jQKpceLPWOa73VZeTo_YidzLQPTuiYMww/edit#heading=h.m8tb4sywqpzy) doc.

**Comment by color2life** [comment]
@kaelig I sent an email twice to both emails seems lots, is there anything I can help you with?

**Comment by EisenbergEffect** [comment]
@kaelig Congrats on the kickoff 🎊 

Microsoft is looking to get more involved with the DTCG. We're members of the group and would love to participate in future meetings. I don't have capacity to function as an editor at this time, but would love to get various members of my team involved in other ways. What's the best way to jump in?

**Comment by kaelig** [comment]
@color2life thank you for the ping! I answered your email ✅ 

@EisenbergEffect Hey Rob, that's awesome 🎉 Editors are currently drafting a first editor's draft, and we'll involve the community (a small part at first, and publicly shortly after) + vendors for rounds of reviews/discussions. I'll make sure you guys have an opportunity to jump in during the early phase, alongside vendors. Does that sound good?

**Comment by jacobtyq** [comment]
Hey @kaelig , I previously applied as an editor via the call for editor doc. I realized I might not have the capacity to function as an editor for now but would love to be involved in this in other ways still. How can I contribute?

**Comment by gqio** [comment]
Hey @kaelig,

Exactly same as Jacob on my side.
How can I help/contribute ?

Best

**Comment by EisenbergEffect** [comment]
@kaelig That sounds great. Thank you 😄

**Comment by blackfalcon** [comment]
This is great work. I am very much looking forward to the discussion regarding the models that will be used to influence the implementation standard to come. I am very much looking forward to a day where development and design alike can look to a standard spec for implementation to bridge this gap.

**Comment by kaelig** [comment]
Closing as part of an issue clean up.
