### ISSUE TITLE
Universal Design Tokens?

### ISSUE THREAD

**Issue by guiseek** [design-tokens/community-group#45]
have you seen this? https://udt.design what do you think about?

**Comment by gearsandcode** [comment]
That’s the work of James Nash. He’s active here and was the person that directed me here.

**Comment by guiseek** [comment]
Cool, I liked this idea

**Comment by kaelig** [comment]
Thank you Jesse! @c1rrus is indeed on the team of editors and very active.

**Comment by c1rrus** [comment]
Indeed.

The DTCG format spec we're working on achieves the same thing I set out to do with UDT, but with much greater community participation and support. :-)

Our current, internal draft spec isn't too far away from what I had been experimenting with for the UDT format, so I'm hoping might be able to take the parser/serialiser code I had started and make it implement the DTCG format. 🤞
