### ISSUE TITLE
[Format] Token value - string, number, array, object?

### ISSUE THREAD

**Issue by kevinmpowell** [design-tokens/community-group#58]
JSON supports string, number, array and object as data types. Which of these do we want to support for token _values_.

String:
```
{
  colorTextPrimary: {
    value: '#000000'
  }
}
```

Number:
```
{
  durationDefault: {
    value: 10
  }
}
```

Array:
```
{
  breakpoints: {
    value: ['320', '640', 1080]
  }
}  
```

Object:
```
{
  textHeadingLevel1: {
    value: {
      fontSize: 32
      fontWeight: 700
      lineHeight: 1.5
    }
  }
}
```

I suspect we'll need to support all four data types.

**Comment by c1rrus** [comment]
I'd say a token's value can potentially be any of the JSON types (also including `boolean` and `null`).

Of course, each of the DTCG types we define in our spec (`color`, `dimension`, `duration`, etc.) specifies exactly how values of that type must be formatted. So, when using those types (which I suspect most tokens would), we are narrowing down which underlying JSON type(s) those values can be. E.g. `color` values can only ever be JSON strings.

However, types we add in future and/or iterations of the current types may well be built on the full range of JSON types, so I see no reason to artificially limit their use.

Besides, this rule from the [Types section](https://design-tokens.github.io/community-group/format/#types) pretty much necessitates all JSON types being available:

>If the type property is absent, tools MUST treat values as one of the basic JSON types and not attempt to infer any other type from the value.

**Comment by kevinmpowell** [comment]
@c1rrus I agree. I don't think we need to belabor this topic. I'll get a PR together to update the spec with this information so we can close this issue out.
