### ISSUE TITLE
Token name case sensitivity

### ISSUE THREAD

**Issue by kevinmpowell** [design-tokens/community-group#59]
## Should token names be case sensitive?
```
{
  colorTextPrimary: {
    value: '#000000'
  },
  ColorTextprimary: {
    value: '#000000'
  }
}
```

Should the above be two valid token keys (case-sensitive) or a duplicate entry (case-insensitive)?

**Comment by mattfelten** [comment]
From a linting perspective, I'd want that example to give a warning. Thinking about a name translation standpoint, e.g camel case to kebab case, those two names would be translated differently, `color-text-primary` and `-color-textprimary` respectively, and I'd expect that. So they are unique to me.

My vote is case-sensitive

**Comment by ariarzer** [comment]
I vote for the case-sensitive token's names. It will better for linting and consistency.
And, when it will translate for CSS custom property, for example, will be easy to linting a css-code too.

**Comment by kevinmpowell** [comment]
> I'd want that example to give a warning

@mattfelten I completely agree. I think that may be sufficient. There may be environments that are case-insensitive where tokens would be used, but I can't think of any and those who operate in those environments can adapt as necessary.

**Comment by dbanksdesign** [comment]
I agree with @kevinmpowell and @mattfelten case-sensitive, but the spec should include a warning about potential name collisions and how toolmakers should deal with it.

**Comment by ChucKN0risK** [comment]
Reviewed by the spec editors on 2021-11-02

**Decision**
The spec should include a warning about potential name collisions and how toolmakers should deal with it.

**Action to be taken**
Next version of specification will reflect these decisions.

We’re closing this issue for now, but may reopen it in the future if needed.
