### ISSUE TITLE
Disambiguate RFC 2119 keywords where appropriate

### ISSUE THREAD

**Issue by kaelig** [design-tokens/community-group#77]
Adhere to and credit RFC 2119 Key words for use in RFCs to Indicate Requirement Levels [[KEYWORDS](https://www.ietf.org/rfc/rfc2119.txt)] (e.g., "MUST", "MUST NOT", "REQUIRED").

When these keywords are used in the RFC sense, make them UPPERCASE.

The author may explain why if these keywords are not used in the RFC sense.

Where they are not required for interoperation or to limit behavior which has potential for causing harm these keywords must not be used to try to impose a particular method on implementors where the method is not required for interoperability.

Source: https://www.w3.org/Guide/manual-of-style/#RFC

### Example of fix needed

For example, in the [Description section](https://design-tokens.github.io/community-group/format/#description):

>The description property ~must~ MUST be a plain JSON string, for example:

![Screen Shot 2021-09-20 at 5 23 33 PM](https://user-images.githubusercontent.com/85783/134093874-9d5c951a-ea26-43a5-9fff-0642904c97fd.png)

---

### Exceptions

This doesn't impact notes and issues (as they are informative, not normative).

For example, this usage of "should" is acceptable 👍🏻 

![Screen Shot 2021-09-20 at 5 25 31 PM](https://user-images.githubusercontent.com/85783/134094222-5a651ab7-f89f-425d-b94f-24f707bd434f.png)

**Comment by ChucKN0risK** [comment]
I’ve reviewed this and have nothing to add/trust the others for the outcomes.

**Comment by kevinmpowell** [comment]
I’ve reviewed this and have nothing to add/trust the others for the outcomes.

**Comment by dbanksdesign** [comment]
Ditto what they said  ☝️

**Comment by donnavitan** [comment]
I’ve reviewed this and have nothing to add/trust the others for the outcomes.
