### ISSUE TITLE
Affiliation to a standards body or other foundation

### ISSUE THREAD

**Issue by kaelig** [design-tokens/community-group#8]
To ensure discussions in the DTCG lead to open-source / open-standards, and intellectual property can’t be derived out of it, I am looking into affiliating the DTWG to an existing standards body or foundation that will be able to issue a license, as well as provide some structure / legitimacy to this working group.

The W3C came up as a good place to create a community group, so I’ll be investigating this first.

I’m also in touch with experts who’ve been working on open standards for the past few decades, see if they have other suggestions.

I’ll be updating this post with the latest news over the next few weeks.

Please let me know in the comments below if you’re aware of foundations/consortiums that could host the DTCG.

**Comment by c1rrus** [comment]
If the W3C could host us, that'd be amazing. Failing that, maybe we could try the [IETF](https://www.ietf.org/).

**Comment by kaelig** [comment]
@c1rrus I looked at the IETF and it looks like their areas of interest don't intersect with a specification around design tokens. Am I missing something?

**Comment by c1rrus** [comment]
Yeah, maybe they're not such a good fit.
I thought they had standardised a number of file formats. I just had a quick look and, while there are some like vCard, iCalendar and some flavours of TIFF, that kind of thing doesn't seem to be their main focus.

**Comment by kaelig** [comment]
I just heard back from @dontcallmedom at the w3c, who says that a W3C Community Group would be a great fit to host the Design Tokens Working Group.

I'm in the process of checking the terms with a Shopify legal counsel, and getting approval from my leadership to take this group to the next level.

**Comment by c1rrus** [comment]
Amazing!

**Comment by kaelig** [comment]
To avoid confusion with actual W3C working groups, I am renaming this project from the Design Tokens Working Group to the Design Tokens Community Group.

**Comment by kaelig** [comment]
Important: this project is now an official [W3C Community Group](https://www.w3.org/community/design-tokens) 🎉 

[Read the group's charter](https://github.com/design-tokens/community-group/blob/master/CHARTER.md)

As per the charter:

>Community Group participants agree to make all contributions in the GitHub repo the group is using for the particular document. This may be in the form of a pull request (preferred), by raising an issue, or by adding a comment to an existing issue.

All documents in this Repository are licensed by contributors
under the [W3C Document License](https://www.w3.org/Consortium/Legal/copyright-documents).

To make _substantive_ contributions to specifications, you must either join the Design Tokens W3C Community Group or make a non-member patent licensing commitment.

In order to join the group, you will need a W3C account. Please note, however, that W3C Membership is not required to join a Community Group – [detailed instructions](https://www.w3.org/community/design-tokens/2019/07/31/call-for-participation-in-design-tokens-community-group/).

## Next step: choosing a chair

Chairs will facilitate discussion to try to resolve the objection according to the [decision process](http://w3c.github.io/cg-charter/CGCharter.html#decision).

In the next few days/weeks, we will [choose a chair](https://www.w3.org/community/about/tool/#choose-chair) for the community group. Unless my employer's legal counsel doesn't approve it, I'll be running for the position. @jina will run for co-chair. If anyone in the Community Group would like to run as well, they'll have a chance to do so very soon.

---

Let me know in the comments below if you have any questions.
